/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_openfuture_api_jni_Aes */

#ifndef _Included_io_openfuture_api_jni_Aes
#define _Included_io_openfuture_api_jni_Aes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_openfuture_api_jni_Aes
 * Method:    encryptAes
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_openfuture_api_jni_Aes_encryptAes
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     io_openfuture_api_jni_Aes
 * Method:    decryptAes
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_openfuture_api_jni_Aes_decryptAes
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
