name: Building JVM shared library

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Install system dependencies
      run: |
        sudo apt-get update && sudo apt-get install ninja-build libboost-all-dev --fix-missing
    - name: Cache internal dependencies
      id: internal_cache
      uses: actions/cache@v1.1.2
      with:
        path: build/local
        key: ${{ runner.os }}-internal-${{ hashFiles('tools/install-dependencies') }}
    - name: Install internal dependencies
      run: |
        tools/install-dependencies
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
      if: steps.internal_cache.outputs.cache-hit != 'true'
    - name: Code generation
      run: |
        tools/generate-files
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
    - name: CMake
      run: |
        cmake -H. -Bbuild
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
    - name: Build TrustWalletCore
      run: |
        make -Cbuild -j12 TrustWalletCore
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
        CK_TIMEOUT_MULTIPLIER: 4
    - name: Build JNI shared library
      run: |
        cd openplatform
        cmake . -DCMAKE_BUILD_TYPE=Debug
        make
    - name: Discover action
      run: |
        whoami
        pwd
        ls -la
    - name: Deploy artifact to Open Key server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./openplatform/libtrust-core-jvm.so
        remote: /usr/lib/libtrust-core-jvm.so
        host: ${{ secrets.OPEN_KEY_HOST }}
        privateKey: ${{ secrets.OPEN_KEY_SSH_PRIVATE_KEY }}
